 
GET http://localhost:8080/student/8b7ceea3-e5c8-45ac-be7d-06430652459d/course/ HTTP/1.1
    'Content-Type': 'application/json',
    'Accept': 'application/json'

# GET http://localhost:8080/course/8e5c07fe-a99c-4093-8b33-550224c99b91/student/ HTTP/1.1
#     'Content-Type': 'application/json',
#     'Accept': 'application/json'
  

# POST http://localhost:8080/course/8bec06b8-482f-4441-91be-e054d0096e68/student/8b7ceea3-e5c8-45ac-be7d-06430652459d HTTP/1.1




# DELETE http://localhost:8080/course/ab97367a-2739-4863-a4ea-4db6c264d72e HTTP/1.1 HTTP/1.1

# PUT http://localhost:8080/course?course_name=React HTTP/1.1
#  Content-Type: application/json
# Accept-Language: en-us

# {
#    "Course_name":"Anguler",
#    "Is_ready":false
# }


# GET http://localhost:8080/course/e0cf2c14-4516-495f-ba2e-ebad798a8d95 HTTP/1.1
#  Content-Type: application/json
# Accept-Language: en-us

#  {
#       "Id":"e0cf2c14-4516-495f-ba2e-ebad798a8d95"
#  }




#  POST  http://localhost:8080/student/ HTTP/1.1 
 Content-Type: application/json
 Accept-Language: en-us


 {
   "Name":"sari Horvitz",
   "Phone_number":"0547813243",
   "Email":"sariddd@ami.org.il"
 }


#  POST  http://localhost:8080/lecturer/ HTTP/1.1 
#  Content-Type: application/json
#  Accept-Language: en-us


#  {
#    "Name":"mos",
#    "Phone_number":"0644847465",
#    "Email":"david@ami.org.il"
#  }








#  GET  http://localhost:8080/course/:courseId HTTP/1.1 

   #  "ID":"e0cf2c14-4516-495f-ba2e-ebad798a8d95"





# Content-Type: application/json
# Accept-Language: en-us


# {
#    "Course_name" :"david",
# }

#  POST  http://localhost:8080/course HTTP/1.1 
# Content-Type: application/json
# Accept-Language: en-us


#  {
#     "Course_name":"Java Script",
#     "Starting_date": "2023-02-01",
#     "End_date": "2023-05-01",
#     "Minimum_pass_score" :10,
#      "Maximum_students": 30,
#     "Is_ready":false
#  }